### ISSUE TITLE
How to close menu when you click on a link?

### ISSUE THREAD

**Issue by guillaumew** [mahmutduva/angular-aside-menu#12]
On your demo, it would be clicking on an element with the class "list-group-item" : 
http://plnkr.co/edit/1ALqm5MRDtdwsFBN1OYm?p=preview

I'd like this click to close menu and change content. I tried to add the attribute
aside-menu-toggle="left-menu"

but the backdrop is still visible.

**Comment by mahmutduva** [comment]
You can check it now. Please answer me, thanks for your attention.

**Comment by guillaumew** [comment]
It seems to work.
Thank you so much!
