### ISSUE TITLE
aside-menu in angular2

### ISSUE THREAD

**Issue by sekko970** [mahmutduva/angular-aside-menu#15]
Hi, i am trying to include your component inside angular2 application.
Could you help me?

**Comment by mahmutduva** [comment]
I don't suggest using this component inside angular2 application. You can find component which developed for angular2 application. I am developing aside menu for angular2 application, but not ready yet.

**Comment by mahmutduva** [comment]
@sekko970 https://github.com/mahmutduva/ng2-aside,
You can use ng2-aside in angular2 application.
