### ISSUE TITLE
Scroll content in aside-menu-content

### ISSUE THREAD

**Issue by Kinzi** [mahmutduva/angular-aside-menu#16]
Hi!

Is there a way to have the content in <aside-menu-content> scrollable?
You can see the issue here in your demo as well:
http://plnkr.co/edit/1ALqm5MRDtdwsFBN1OYm?p=preview
the content just gets cut off at the bottom when you adjust the window height to something like 600px...

Thanks!

**Comment by mahmutduva** [comment]
@Kinzi You can check it now. Thanks for your attention

**Comment by Kinzi** [comment]
sweet! thanks for fixing this so quick! :) 👍
