### ISSUE TITLE
Live demo outdated

### ISSUE THREAD

**Issue by browniebroke** [mahmutduva/angular-aside-menu#8]
The live demo seems to have several issues:
- It's referencing a copy of the script, frozen at v1.0.0, would be more accurate if it was including the latest javascript from master, therefore serving as testing page.
- It's including the scripts after the closing `</body>` tag, they should be before (Plunkr is showing an error).
- It's including bootstrap's javascript, which requires jQuery, and therefore raises an error. However, bootstrap.js isn't required, only the CSS is.

If I reference the version as per [v1.0.0 commit](https://github.com/mahmutduva/angular-aside-menu/tree/883223e1e8f0eb31c5ea1036533b33895f3b8ef7), and fix the 2 last issues [it works](http://plnkr.co/edit/JoC5v6Ut6kx6zSZcXilD?p=preview). However, if I try to use the latest version of the source to fix the first item, [it breaks](http://plnkr.co/edit/twmFPwUmzmqndJclCpCr?p=preview).

**Comment by mahmutduva** [comment]
Thank you for your attention. I care about the issues that you noticed. I will fix them as soon as possible.

**Comment by browniebroke** [comment]
I'm happy to fix it myself, just seeking if you have any preference on how
to proceed on that?

**Comment by mahmutduva** [comment]
I fixed these problems, you can check it. If you want to improve features, you can create pull request. Thank you.

**Comment by browniebroke** [comment]
Thanks!
